# docker-compose.yml

version: "3.9"

services:
  web:
    build:
      context: .
    container_name: circle3lab-web
    ports:
      - "5000:80"
    volumes:
      - ./media:/app/wwwroot/media
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "P@ssw0rd123Circle"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
